[package]
name = "pam-parallel-fprint"
version = "1.0.0"
edition = "2021"
authors = ["Selim Cifci"]
description = "A Linux-PAM module that allows for fingerprint (fprintd) and password authorization in parallel"
license = "GPL-3.0"

[[lib]]
name = "pam_parallel_fprint"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pam = "0.7"
zbus = { version = "4.0", default-features = false, features = ["blocking"] }
tokio = { version = "1", features = ["rt", "sync", "time"] }
syslog = "6.1"
log = "0.4"
libc = "0.2"
thiserror = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 0

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
all = "warn"
